/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      fontFamily: {
        roboto: ['"Roboto"', 'sans-serif'],
        poppins: ['"Poppins"', 'sans-serif'],
        'open-sans': ['"Open Sans"', 'sans-serif'],
        montserrat: ['"Montserrat"', 'sans-serif'],
        raleway: ['"Raleway"', 'sans-serif'],
        oswald: ['"Oswald"', 'sans-serif'],
        lobster: ['"Lobster"', 'cursive'],
        'source-sans-pro': ['Ponnala, ', 'sans-serif'],
        ubuntu: ['"Ubuntu"', 'sans-serif'],
        merriweather: ['"Merriweather"', 'serif'],
        lato: ['"Lato"', 'sans-serif'],
        nunito: ['"Nunito"', 'sans-serif'],
        'abril-fatface': ['"Abril Fatface"', 'serif'],
        'acme': ['"Acme"', 'sans-serif'],
        'aldrich': ['"Aldrich"', 'sans-serif'],
        'alex-brush': ['"Alex Brush"', 'cursive'],
        'amatic-sc': ['"Amatic SC"', 'cursive'],
        'angilla': ['"Angilla"', 'sans-serif'],
        'anton': ['"Anton"', 'sans-serif'],
        'arvo': ['"Arvo"', 'serif'],
        'bangers': ['"Bangers"', 'cursive'],
        'barlow': ['"Barlow"', 'sans-serif'],
        'barlow-condensed': ['"Barlow Condensed"', 'sans-serif'],
        'baskervville': ['"Baskervville"', 'serif'],
        'bebas-neue': ['"Bebas Neue"', 'sans-serif'],
        'bitter': ['"Bitter"', 'serif'],
        'bree-serif': ['"Bree Serif"', 'serif'],
        'bungee': ['"Bungee"', 'sans-serif'],
        'cabin': ['"Cabin"', 'sans-serif'],
        'candal': ['"Candal"', 'sans-serif'],
        'cardo': ['"Cardo"', 'serif'],
        'chewy': ['"Chewy"', 'cursive'],
        'chivo': ['"Chivo"', 'sans-serif'],
        'coda': ['"Coda"', 'sans-serif'],
        'comfortaa': ['"Comfortaa"', 'sans-serif'],
        'copse': ['"Copse"', 'serif'],
        'courgette': ['"Courgette"', 'cursive'],
        'dancing-script': ['"Dancing Script"', 'cursive'],
        'droid-sans': ['"Droid Sans"', 'sans-serif'],
        'droid-serif': ['"Droid Serif"', 'serif'],
        'eb-garamond': ['"EB Garamond"', 'serif'],
        'ek-madhvani': ['"Ek Madhvani"', 'sans-serif'],
        'ekrond': ['"Ekrond"', 'serif'],
        'exo': ['"Exo"', 'sans-serif'],
        'exo-2': ['"Exo 2"', 'sans-serif'],
        'fira-sans': ['"Fira Sans"', 'sans-serif'],
        'fira-mono': ['"Fira Mono"', 'monospace'],
        'francois-one': ['"Francois One"', 'sans-serif'],
        'fredoka-one': ['"Fredoka One"', 'cursive'],
        'gaegu': ['"Gaegu"', 'serif'],
        'galada': ['"Galada"', 'sans-serif'],
        'gentium-basic': ['"Gentium Basic"', 'serif'],
        'gloock': ['"Gloock"', 'sans-serif'],
        'gloria-hallelujah': ['"Gloria Hallelujah"', 'cursive'],
        'great-vibes': ['"Great Vibes"', 'cursive'],
        'habibi': ['"Habibi"', 'sans-serif'],
        'hammersmith-one': ['"Hammersmith One"', 'sans-serif'],
        'handlee': ['"Handlee"', 'cursive'],
        'hanna': ['"Hanna"', 'sans-serif'],
        'hardwell': ['"Hardwell"', 'sans-serif'],
        'heebo': ['"Heebo"', 'sans-serif'],
        'helvetica': ['"Helvetica"', 'sans-serif'],
        'hollywood': ['"Hollywood"', 'cursive'],
        'iceland': ['"Iceland"', 'sans-serif'],
        'inconsolata': ['"Inconsolata"', 'monospace'],
        'indie-flower': ['"Indie Flower"', 'cursive'],
        'inspiration': ['"Inspiration"', 'cursive'],
        'italiana': ['"Italiana"', 'serif'],
        'julius-sans-one': ['"Julius Sans One"', 'sans-serif'],
        'kamila': ['"Kamila"', 'serif'],
        'karla': ['"Karla"', 'sans-serif'],
        'katibeh': ['"Katibeh"', 'serif'],
        'kavivanar': ['"Kavivanar"', 'cursive'],
        'khand': ['"Khand"', 'sans-serif'],
        'kosugi': ['"Kosugi"', 'sans-serif'],
        'lato': ['"Lato"', 'sans-serif'],
        'lora': ['"Lora"', 'serif'],
        'lucida-grande': ['"Lucida Grande"', 'sans-serif'],
        'manrope': ['"Manrope"', 'sans-serif'],
        'maven-pro': ['"Maven Pro"', 'sans-serif'],
        'merriweather': ['"Merriweather"', 'serif'],
        'muli': ['"Muli"', 'sans-serif'],
        'nanum-gothic': ['"Nanum Gothic"', 'sans-serif'],
        'oceanic': ['"Oceanic"', 'sans-serif'],
        'overpass': ['"Overpass"', 'sans-serif'],
        'patua-one': ['"Patua One"', 'serif'],
        'permanent-marker': ['"Permanent Marker"', 'cursive'],
        'playfair-display': ['"Playfair Display"', 'serif'],
        'poppins': ['"Poppins"', 'sans-serif'],
        'raleway': ['"Raleway"', 'sans-serif'],
        'roboto': ['"Roboto"', 'sans-serif'],
        'satisfy': ['"Satisfy"', 'cursive'],
        'scada': ['"Scada"', 'sans-serif'],
        'signika': ['"Signika"', 'sans-serif'],
        'sigmar-one': ['"Sigmar One"', 'sans-serif'],
        'slabo-27px': ['"Slabo 27px"', 'serif'],
        'spartan': ['"Spartan"', 'sans-serif'],
        'stone-sans': ['"Stone Sans"', 'sans-serif'],
        'teko': ['"Teko"', 'sans-serif'],
        'title': ['"Title"', 'serif'],
        'ubuntu': ['"Ubuntu"', 'sans-serif'],
        'ultra': ['"Ultra"', 'sans-serif'],
        'volkhov': ['"Volkhov"', 'serif'],
        'zilla-slab': ['"Zilla Slab"', 'serif'],
      },
    },
  },
  plugins: [],
};

// *****************
      


  

